# -*- coding: utf-8 -*-
"""prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQxpKlJaEcYfFOpA-IDeBXqznm-QOnQI
"""

import numpy as np
alnif = np.random.randint(10000000, size = 1)
nifdig = np.random.randint(10, size = 3)
def certificado():
  print("----------------------")
  print("Fecha de nacimiento: 10/2/1994")
  print("Soltero")
  print("No pertenece a la Unión Europea")
  print(f"NIF: {alnif}-{nifdig}")
  print("Jose Enrique Segundo ")
  print("----------------------")


def personaR():
  return(f"{buscar}-A2T", "Jorge Gonzales", "69", "No pertence a la Unión Europea"  )
#print(personaR())
#print(alnif)
#print(lanif)
def menu():
  print("Bienvenido a NIF")
  print("Seleccione la accion que desea utilizar: ")
  print("(1) Guardar datos")
  print("(2) Buscar una persona")
  print("(3) Imprimir certificados")
  print("(4) Salir de la apliacion")
menu()

seleccion = int (input(" "))
while seleccion < 1 or seleccion > 4:
  seleccion = int (input(" "))
if seleccion == 1:
  print("Selecciono grabar datos, porfavor los datos a continuacion.")
  print("Ingrese los primeros 8 digitos de su nif")
  nif = int (input())
  print("Ingrse los ultimos 3 caracteres del nif")
  canif = input()
  print("Ingrese su nombre")
  nombre = input()
  print("Ingrese su edad")
  edad = int (input())
  while edad < 1:
    edad = int (input())
def datos():
  return (f"{nif} {canif} {nombre} {edad}")
if seleccion == 1:
  print(f"Estos son sus datos guardados")
  print(datos())
  print("-----------------")
if seleccion == 2:
  print("Selecciono buscar, ingrese los primeros 8 digitos de un nif")
  buscar = int (input( ))
  print(personaR())
  print("-----------------")
if seleccion == 3:
  print("Selcciono imprimir certificados")
  print(certificado())
  print("-----------------")
if seleccion == 4: print("Decidio salir del programa, Adios.")